apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test-nginx
  namespace: kube-system   # <- change to "default" in the second test if you want
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-test-nginx
  template:
    metadata:
      labels:
        app: argocd-test-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
