# applications:
#   - name: my-sample-app
#     namespace: ats-backend-service
#     project: ats
#     repoURL: https://github.com/elahe412/argocd-application.git
#     targetRevision: main
#     path: /aoa-sample/app-af-apps/my-app
#     destinationNamespace: ats-test-service
applications:
- name: aoa-application
  namespace: ats-aoa
  project: ats
  enabled: true
  destinationNamespace: ats-apps
  path: aoa-sample/my-app
  repoURL: https://github.com/elahe412/argocd-application.git
  targetRevision: main

